name: amp
description: MalmÃ¶ Parking Alerts - Android App
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  geolocator: ^10.0.0
  permission_handler: ^11.4.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
