[toolchain]
channel = "nightly-2026-01-12"
components = ["rustfmt", "clippy", "rust-src"]
targets = [
    "aarch64-unknown-linux-gnu",
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "x86_64-unknown-linux-gnu",
]
profile = "minimal"
