[package]
name = "amp-android"
version.workspace = true
edition = "2024"
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
amp-core = { path = "../core" }
jni = { workspace = true }
lazy_static = { workspace = true }
tracing = { workspace = true }
