[application]
name = "amp"
publisher = "Skäggbyrån Malmö"
version = "1.0.0"

[bundle]
icon = ["assets/icon/icon-512.png"]

[android]
targets = ["arm64-v8a", "arm64-v7a", "x86_64", "x86"]
min_sdk = 24
target_sdk = 36